import '~/styles/globals.css'

import { Inter as FontSans } from 'next/font/google'
import { cookies } from 'next/headers'

import { TRPCReactProvider } from '~/trpc/react'
import { type ReactNode } from 'react'
import { cn } from '~/lib/utils'
import { AuthGuard, AuthProvider } from '~/components'

const fontSans = FontSans({
    subsets: ['latin'],
    variable: '--font-sans',
})

export const metadata = {
    title: 'Create T3 App',
    description: 'Generated by create-t3-app',
    icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

export default function RootLayout({ children }: { children: ReactNode }) {
    return (
        <html lang="en">
            <body className={cn(
                'min-h-screen bg-background font-sans antialiased',
                fontSans.variable,
            )}>
                <TRPCReactProvider cookies={cookies().toString()}>
                    <AuthProvider>
                        <AuthGuard>
                            {children}
                        </AuthGuard>
                    </AuthProvider>
                </TRPCReactProvider>
            </body>
        </html>
    )
}
