import '~/styles/globals.css'

import { Analytics } from '@vercel/analytics/react'
import { SpeedInsights } from '@vercel/speed-insights/next'
import { Inter as FontSans } from 'next/font/google'
import { type ReactNode } from 'react'

import { Toaster } from '~/components/ui/sonner'
import { cn } from '~/lib/utils'

import { AuthProvider } from './AuthProvider'
import { JotaiProvider } from './JotaiProvider'

const fontSans = FontSans({
    subsets: ['latin'],
    variable: '--font-sans',
})

export const metadata = {
    title: 'Fluent',
    description: 'Generated by create-t3-app',
    icons: [{ rel: 'icon', url: '/logo.svg' }],
}

export default function RootLayout({ children }: { children: ReactNode }) {
    return (
        <html lang="en">
            <body className={cn('min-h-screen bg-background font-sans antialiased', fontSans.variable)}>
                <JotaiProvider>
                    <AuthProvider>
                        {children}
                    </AuthProvider>
                </JotaiProvider>
                <Toaster/>
                <Analytics/>
                <SpeedInsights/>
            </body>
        </html>
    )
}
